# Generated by Django 4.2 on 2023-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('idProblem', models.IntegerField()),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
