# Generated by Django 4.2 on 2023-04-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problem.problem')),
                ('imageSolution', models.ImageField(blank=True, null=True, upload_to='')),
                ('imageSubmit', models.ImageField(blank=True, null=True, upload_to='')),
                ('fileSolution', models.FileField(blank=True, null=True, upload_to='')),
                ('fileSubmit', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('problem.problem',),
        ),
    ]
