# Generated by Django 4.2 on 2023-04-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
        ('chess', '0002_rename_filesolution_chessproblem_filechessproblem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solution.solution')),
                ('imageChessSolution', models.ImageField(blank=True, null=True, upload_to='')),
                ('fileChessSolution', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('solution.solution',),
        ),
    ]
