# Generated by Django 4.2 on 2023-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_chesssolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesssolution',
            name='imageChessSolution',
            field=models.BinaryField(),
        ),
    ]
