# Generated by Django 4.2 on 2023-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_chesssolution_codechesssolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesssolution',
            name='matchingChessSolution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chessproblem',
            name='imageChessProblem',
            field=models.ImageField(blank=True, null=True, upload_to='images/chessProblems/'),
        ),
    ]
