# Generated by Django 4.2 on 2023-04-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_alter_chessproblem_filechessproblem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesssolution',
            name='matchingChessSolution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
