# Generated by Django 4.2 on 2023-04-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='userName',
            field=models.CharField(default='userName', max_length=20),
            preserve_default=False,
        ),
    ]
