# Generated by Django 4.2 on 2023-04-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solved',
        ),
        migrations.AddField(
            model_name='problem',
            name='nameProblem',
            field=models.CharField(default='nameProblem', max_length=20),
            preserve_default=False,
        ),
    ]
