# Generated by Django 4.2 on 2023-04-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_remove_problem_solved_problem_nameproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='userName',
        ),
    ]
