# Generated by Django 4.2 on 2023-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('surnames', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
